### PR TITLE
Build combined installers for cross hosts

### PR DESCRIPTION
**Pull request by alexcrichton**
We've got the docs, cargo, and rustc packages all up and running, so let's start
packing these up so rustup can pick them up as well.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Untested, r? @brson

**Comment by alexcrichton** [comment]
cc @japaric

**Comment by brson** [comment]
r=me

**Comment by alexcrichton** [comment]
I'll deploy this once the current beta builds are finished (probably late tonight or tomorrow)

**Comment by alexcrichton** [comment]
Actually I'm gonna be bold, let's see how `buildbot reconfig` works.

**Pull request merged**
