### PR TITLE
Add rust-analysis manifest

### PR DESCRIPTION
**Pull request by nrc**
r? @brson

### CODE REVIEW

**Comment by alexcrichton** [comment]
I think we'll also want to add this to the optional components (extensions) array of the `rust` package. Or at least I think that rustup interprets that?

**Comment by nrc** [comment]
@alexcrichton @brson added to extensions

**Comment by Arnavion** [comment]
I see this is in 2017-02-03's nightly's manifest, but all the `rust-analysis` entries are associated with `target = "x86_64-unknown-netbsd"`

**Pull request merged**
