### PR TITLE
passwords.py file

### PR DESCRIPTION
**Pull request by bheesham**
Changed to using a `passwords.py` file for storing credentials. This should take care of the whole "passwords being public" thing.

[See this issue.](https://github.com/rust-lang/rust/issues/20629)

### CODE REVIEW

**Comment by bheesham** [comment]
Uuuhhh, ignore this for now. There shouldn't be a merge conflict.

**Comment by nikomatsakis** [comment]
I know very little about this. Changing reviewer to @brson

**Comment by brson** [comment]
I'm not sure this is sufficient. It will allow us to keep the passwords hidden from the source code, but it leaves a few problems:

* It doesn't create any distinction between what credentials are required for triggering e.g. try builds vs those for dist builds, and dist builds are the only ones that need to be restricted to just a few people.
* Passwords are still transmitted over plain text to buildbot.

**Comment by brson** [comment]
A concrete change here might be to distinguish credentials for dist builds from all others. I think we should probably ask the people in #buildbot on freenode about best practices, though perhaps we just need to bite the bullet and put buildbot behind an https proxy.

**Comment by bheesham** [comment]
Putting buildbot behind nginx or something similar was what I was going to
suggest to get around the whole "transferral of passwords over plaintext".

I'll ask on #buildbot later today or tomorrow if I don't get the
information I want from the Buildbot wiki.

**Comment by bheesham** [comment]
It looks like there's some fine-grain control available for this: http://docs.buildbot.net/current/manual/cfg-statustargets.html#authentication

I'll test out the `HTPasswdAuth` method, because that would probably be easier to manage.

**Comment by brson** [comment]
passwords.py seems good

**Comment by bheesham** [comment]
So currently the two changes are:
  * Passwords are in a `passwords.py` file.
  * There are two different users, one that is not allowed to touch anything that has "dist" in it's name, and another one that is.

**Comment by brson** [comment]
Looks good, thanks. Testing it now.

**Comment by brson** [comment]
Thanks @bheesham!

**Pull request merged**
