### PR TITLE
Tweak the linux-cross image

### PR DESCRIPTION
**Pull request by alexcrichton**
* Downgrade arm gcc to 4.7
* Downgrade aarch64 gcc to 4.8
* Install powerpc compilers (4.8)
* Install a rumprun compiler

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @antonblanchard, is there a powerpc64 toolchain for Linux? I was able to find a powerpc and a powerpc64le one, but unfortunately not just a powerpc64. If there's one readily available I wouldn't mind modifying this image and start cranking out nightlies/releases for the target!

**Comment by alexcrichton** [comment]
Ok, deployed this image.

rumprun isn't enabled yet as it needs fixes in std, but should be up soon.

**Comment by antonblanchard** [comment]
Thanks @alexcrichton! gcc-4.8-powerpc-linux-gnu contains a biarch toolchain (ie use powerpc-linux-gnu-gcc -m64 for 64bit). You should just need a libc (libc6-dev-ppc64-powerpc-cross).

**Comment by alexcrichton** [comment]
Oh excellent, I'll try that out, add it to the list of targets, and see what happens.

**Comment by alexcrichton** [comment]
Hm, so in a docker container I get:

```
root@784e90c16040:/# apt-get install gcc-4.8-powerpc-linux-gnu libc6-dev-powerpc-cross libc6-dev-ppc64-powerpc-cross
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6-dev-powerpc-cross is already the newest version.
libc6-dev-ppc64-powerpc-cross is already the newest version.
gcc-4.8-powerpc-linux-gnu is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
root@784e90c16040:/# echo 'int main() {}' > foo.c
root@784e90c16040:/# powerpc-linux-gnu-gcc-4.8 foo.c -m64
/usr/lib/gcc-cross/powerpc-linux-gnu/4.8/../../../../powerpc-linux-gnu/bin/ld: skipping incompatible /usr/lib/gcc-cross/powerpc-linux-gnu/4.8/libgcc.a when searching for -lgcc
/usr/lib/gcc-cross/powerpc-linux-gnu/4.8/../../../../powerpc-linux-gnu/bin/ld: cannot find -lgcc
/usr/lib/gcc-cross/powerpc-linux-gnu/4.8/../../../../powerpc-linux-gnu/bin/ld: skipping incompatible /usr/lib/gcc-cross/powerpc-linux-gnu/4.8/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/lib/gcc-cross/powerpc-linux-gnu/4.8/../../../../powerpc-linux-gnu/bin/ld: skipping incompatible /usr/lib/gcc-cross/powerpc-linux-gnu/4.8/../../../../powerpc-linux-gnu/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/lib/gcc-cross/powerpc-linux-gnu/4.8/../../../../powerpc-linux-gnu/bin/ld: skipping incompatible /usr/powerpc-linux-gnu/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/lib/gcc-cross/powerpc-linux-gnu/4.8/../../../../powerpc-linux-gnu/bin/ld: cannot find libgcc_s.so.1
/usr/lib/gcc-cross/powerpc-linux-gnu/4.8/../../../../powerpc-linux-gnu/bin/ld: skipping incompatible /usr/lib/gcc-cross/powerpc-linux-gnu/4.8/libgcc.a when searching for -lgcc
/usr/lib/gcc-cross/powerpc-linux-gnu/4.8/../../../../powerpc-linux-gnu/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status
```

Perhaps another package is necessary? It also looks like the [`CROSS_PREFIX` in the makefiles](https://github.com/rust-lang/rust/blob/142214d1f2232a4e88ff7bd99951b01f36052c61/mk/cfg/powerpc64-unknown-linux-gnu.mk#L2) may be wrong if it uses the same compiler with just a `-m64` flag

**Comment by antonblanchard** [comment]
Looks like the image might be missing lib64gcc-4.8-dev-powerpc-cross. I can fire up a container tomorrow to verify exactly what needs to be installed.

**Comment by alexcrichton** [comment]
Ah yeah that did the trick!

**Pull request merged**
